/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packet;

import javax.swing.JOptionPane;

/**
 *
 * @author Katerine Forero
 */
public class SmallInterface extends javax.swing.JFrame {

      int bigDog = 10000;
        int mediumDog = 5000;
        int smallDog = 3000;
        double discount = 0.1;
    public SmallInterface() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        total = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        textOne = new javax.swing.JLabel();
        textTwo = new javax.swing.JLabel();
        textThree = new javax.swing.JLabel();
        textFor = new javax.swing.JLabel();
        textFive = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        hours = new javax.swing.JComboBox<>();
        big = new javax.swing.JComboBox<>();
        medium = new javax.swing.JComboBox<>();
        small = new javax.swing.JComboBox<>();
        wailing = new javax.swing.JLabel();
        fund = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total.setEditable(false);
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 80, -1));

        calculate.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        calculate.setText("CALCULAR");
        calculate.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        getContentPane().add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 90, 30));

        textOne.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        textOne.setForeground(new java.awt.Color(255, 255, 255));
        textOne.setText("Cuantas horas de paseo:");
        getContentPane().add(textOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        textTwo.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        textTwo.setForeground(new java.awt.Color(255, 255, 255));
        textTwo.setText("Numero de perros grandes:");
        getContentPane().add(textTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        textThree.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        textThree.setForeground(new java.awt.Color(255, 255, 255));
        textThree.setText("Numero de perros medianos:");
        getContentPane().add(textThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        textFor.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        textFor.setForeground(new java.awt.Color(255, 255, 255));
        textFor.setText("Numero de perros pequeños: ");
        getContentPane().add(textFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        textFive.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        textFive.setText("El costo total a pagar es: ");
        getContentPane().add(textFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        title.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("PASEO DE PERROS");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        hours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 50, -1));

        big.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(big, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 50, -1));

        medium.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 50, -1));

        small.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallActionPerformed(evt);
            }
        });
        getContentPane().add(small, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 50, -1));

        wailing.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        wailing.setText("Lo hice con mis lagrimas profe ;(");
        getContentPane().add(wailing, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 130, 40));

        fund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ivancito.png"))); // NOI18N
        getContentPane().add(fund, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
     try {
    int numPerrosGrandes = Integer.parseInt((String) big.getSelectedItem());
    int numPerrosMedianos = Integer.parseInt((String) medium.getSelectedItem());
    int numPerrosPequenos = Integer.parseInt((String) small.getSelectedItem());
    int numHorasPaseo = Integer.parseInt((String) hours.getSelectedItem());

    int costoBase = (numPerrosGrandes * bigDog) +
                    (numPerrosMedianos * mediumDog) +
                    (numPerrosPequenos * smallDog);

    
    if (numPerrosGrandes + numPerrosMedianos + numPerrosPequenos > 1) {
        costoBase -= costoBase * discount;
    }

    
    int costoTotalCalculado = numHorasPaseo*costoBase;

    total.setText(Integer.toString(costoTotalCalculado)); 

} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Ingrese valores válidos.");
}

    }//GEN-LAST:event_calculateActionPerformed

    private void smallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmallInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmallInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmallInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmallInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmallInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> big;
    private javax.swing.JButton calculate;
    private javax.swing.JLabel fund;
    private javax.swing.JComboBox<String> hours;
    private javax.swing.JComboBox<String> medium;
    private javax.swing.JComboBox<String> small;
    private javax.swing.JLabel textFive;
    private javax.swing.JLabel textFor;
    private javax.swing.JLabel textOne;
    private javax.swing.JLabel textThree;
    private javax.swing.JLabel textTwo;
    private javax.swing.JLabel title;
    private javax.swing.JTextField total;
    private javax.swing.JLabel wailing;
    // End of variables declaration//GEN-END:variables
}
